name:                advent-of-code
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/oskarek/advent-of-code-2018#readme
license:             BSD3
author:              Oskar Ek
maintainer:          oek@kth.se
copyright:           Copyright (c) 2017 Oskar Ek
category:            Web
extra-source-files:
- README.md

ghc-options:
- -Wall

default-extensions:
- TupleSections

dependencies:
  - base >= 4.7 && < 5
  - containers
  - parsec
  - transformers
  - optparse-applicative
  - safe

library:
  source-dirs: src

executables:
  advent-of-code-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - advent-of-code
